name: hm_innova_app
description: "App Asistencia HM INNOVA - versión móvil Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Base de datos / local
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.0
  path_provider: ^2.1.3

  # Fechas e internacionalización (alineado con el SDK)
  intl: ^0.20.2
  timezone: ^0.10.0

  # Cámara / QR / permisos
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.2
  permission_handler: ^11.3.1

  # Notificaciones locales
  flutter_local_notifications: ^19.5.0

  # Ubicación + servicio en segundo plano
  geolocator: ^11.1.0
  flutter_foreground_task: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
