name: hm_innova_app
description: "App Asistencia HM INNOVA - versi贸n m贸vil Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Base de datos / local
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.0
  path_provider: ^2.1.3

  # Fechas e internacionalizaci贸n
  intl: ^0.20.2
  timezone: ^0.10.0

  # C谩mara / QR / permisos
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.2
  permission_handler: ^11.3.1

  # Notificaciones y ubicaci贸n
  flutter_local_notifications: ^19.5.0
  geolocator: ^11.1.0
  flutter_foreground_task: ^6.1.2

  #  SINCRONIZACIN / RED
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  shared_preferences: ^2.5.3

  #  NUEVO: almacenamiento seguro para token Sanctum
  flutter_secure_storage: ^9.0.0

  #  NUEVO: info de dispositivo y UUID l贸gico
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
